### ISSUE TITLE
manual intervention is not working in heaty

### ISSUE THREAD

**Issue by phsdv** [efficiosoft/hass_apps#2]
I have home assistant 63.1 and hass_apps (0.20180209.0)
The  apps.yaml looks like this:
```
verwarming:
  module: hass_apps_loader
  class: HeatyApp

  rooms:

    keuken:
      thermostats:
        climate.keuken:
      schedule:
      - { temp: 16 if app.get_state("input_boolean.verwarming_uit") == "on" else Ignore(), start: "00:00", end: "23:59", weekdays: 1-7 }
      - { temp: 19.5, start: "06:40", end: "07:50", weekdays: 1-7 }
      - { temp: 19.5 if app.get_state("input_boolean.dagje_thuis") == "on" else Ignore(), start: "08:00", end: "14:40", weekdays: 1-7 }
      - { temp: 18.0, start: "08:00", end: "14:40", weekdays: 1-7 }
      - { temp: 19.0, start: "14:40", end: "17:30", weekdays: 1-7 }
      - { temp: 19.5, start: "17:30", end: "19:00", weekdays: 1-7 }
      - { temp: 17.5, start: "19:00", end: "21:00", weekdays: 1-7 }
      - { temp: 16 }
```
If the input_boolean,dagje_thuis is switch on at 9am, the schedule is not changing to 19,5 degrees but staying on 18 degrees.  Is this a bug or am I doing something wrong. More general can I change a flag during the schedule in a statement like this: `temp: 19.5 if app.get_state("input_boolean.dagje_thuis") == "on" else Ignore(), start: "08:00", end: "14:40"` or should that be done before it starts (before 08:00 in this example?) If the later is the case, I would say that is a bug.
